`include "ctrl_encode_def.v"

// data memory (BRAM-friendly)
// NOTE: This implementation uses synchronous read from BRAM (1-cycle read latency).
module dm(
  input         clk,
  input         DMWr,
  input  [31:0] addr,
  input  [31:0] din,
  input  [2:0]  DMType,
  output reg [31:0] dout
);

  // Keep this size aligned with sample project capacity.
  localparam DMEM_BYTES = 131072;  // 128 KiB
  localparam DMEM_WORDS = DMEM_BYTES / 4;

  // BRAM data array: 32-bit word addressed
  (* ram_style = "block" *) reg [31:0] dmem_reg [0:DMEM_WORDS - 1];

  reg [31:0] rd_word;

  wire [15:0] word_addr = addr[17:2];
  wire [1:0]  byte_off  = addr[1:0];

  integer i;
  initial begin
    for (i = 0; i < DMEM_WORDS; i = i + 1) begin
      dmem_reg[i] = 32'h00000000;
    end
    // Word-packed little-endian memory image generated by build scripts.
    $readmemh("prog1_word.hex", dmem_reg);
  end

  // Write on posedge
  always @(posedge clk) begin
    if (DMWr && (word_addr < DMEM_WORDS)) begin
      case (DMType)
        `dm_word: begin
          dmem_reg[word_addr] <= din;
        end

        `dm_halfword: begin
          if (byte_off[1]) begin
            dmem_reg[word_addr][31:16] <= din[15:0];
          end else begin
            dmem_reg[word_addr][15:0] <= din[15:0];
          end
        end

        `dm_byte: begin
          case (byte_off)
            2'b00: dmem_reg[word_addr][7:0]   <= din[7:0];
            2'b01: dmem_reg[word_addr][15:8]  <= din[7:0];
            2'b10: dmem_reg[word_addr][23:16] <= din[7:0];
            2'b11: dmem_reg[word_addr][31:24] <= din[7:0];
            default: ;
          endcase
        end

        default: begin
        end
      endcase
    end
  end

  // Half-cycle read path: capture memory data on negedge.
  // This provides near-asynchronous behavior to the CPU pipeline.
  always @(negedge clk) begin
    if (word_addr < DMEM_WORDS) begin
      rd_word <= dmem_reg[word_addr];
    end else begin
      rd_word <= 32'h00000000;
    end
  end

  // Load data formatting / sign extension
  always @(*) begin
    case (DMType)
      `dm_word: begin
        dout = rd_word;
      end

      `dm_halfword: begin
        dout = byte_off[1] ? {{16{rd_word[31]}}, rd_word[31:16]}
                           : {{16{rd_word[15]}}, rd_word[15:0]};
      end

      `dm_halfword_unsigned: begin
        dout = byte_off[1] ? {16'h0000, rd_word[31:16]}
                           : {16'h0000, rd_word[15:0]};
      end

      `dm_byte: begin
        case (byte_off)
          2'b00: dout = {{24{rd_word[7]}}, rd_word[7:0]};
          2'b01: dout = {{24{rd_word[15]}}, rd_word[15:8]};
          2'b10: dout = {{24{rd_word[23]}}, rd_word[23:16]};
          2'b11: dout = {{24{rd_word[31]}}, rd_word[31:24]};
          default: dout = 32'h0;
        endcase
      end

      `dm_byte_unsigned: begin
        case (byte_off)
          2'b00: dout = {24'h0, rd_word[7:0]};
          2'b01: dout = {24'h0, rd_word[15:8]};
          2'b10: dout = {24'h0, rd_word[23:16]};
          2'b11: dout = {24'h0, rd_word[31:24]};
          default: dout = 32'h0;
        endcase
      end

      default: begin
        dout = rd_word;
      end
    endcase
  end

endmodule
